### ISSUE TITLE
Fatal bei Aktivierung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faudir#62]
```
Array
(
    [level] => FATAL
    [message] => Uncaught Error: Cannot use object of type stdClass as array in .../wp-content/plugins/rrze-faudir/includes/utils/faudir_utils.php:11
    [datetime] => 22-Oct-2024 10:45:08 UTC
    [details] => Array
        (
            [0] => Uncaught Error: Cannot use object of type stdClass as array in .../wp-content/plugins/rrze-faudir/includes/utils/faudir_utils.php:11
            [1] => Stack trace:
            [2] => #0 .../wp-content/plugins/rrze-faudir/includes/utils/faudir_utils.php(20): FaudirUtils::isUsingNetworkKey()
            [3] => #1 .../wp-content/plugins/rrze-faudir/includes/utils/api-functions.php(105): FaudirUtils::getKey()
            [4] => #2 .../wp-content/plugins/rrze-faudir/rrze-faudir.php(232): fetch_fau_persons_atributes()
            [5] => #3 .../wp-includes/class-wp-hook.php(324): migrate_person_data_on_activation()
            [6] => #4 .../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
            [7] => #5 .../wp-includes/plugin.php(517): WP_Hook->do_action()
            [8] => #6 .../wp-admin/includes/plugin.php(703): do_action()
            [9] => #7 .../wp-admin/plugins.php(60): activate_plugin()
            [10] => #8 {main}  thrown in .../wp-content/plugins/rrze-faudir/includes/utils/faudir_utils.php on line 11
        )

    [ocurrencies] => 1
)
```

Umgebung: PHP: 8.2.18, WP 6.6.2

**Comment by xwolfde** [comment]
Site-Options sind Objekte, kein Array. 
Fixed
